### ISSUE TITLE
MySQL Communications link failure

### ISSUE THREAD

**Issue by NeadApTar** [StaticFX/DiscordBotBungee#7]
Don't tell me I entered something wrong. The previous version had the same error. I thought I had something with the DB, but it's a plugin problem. I don't remember exactly how I fixed it, but I just changed the data in the config several times, added ` '` or removed it, and just wrote all DB data manually.

```21.07 20:21:55 [Server] SEVERE com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
21.07 20:21:55 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
21.07 20:21:55 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21.07 20:21:55 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
21.07 20:21:55 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21.07 20:21:55 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
21.07 20:21:55 [Server] SEVERE at sun.reflect.GeneratedConstructorAccessor78.newInstance(Unknown Source)
21.07 20:21:55 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21.07 20:21:55 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
21.07 20:21:55 [Server] SEVERE at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
21.07 20:21:55 [Server] SEVERE at java.sql.DriverManager.getConnection(DriverManager.java:664)
21.07 20:21:55 [Server] SEVERE at java.sql.DriverManager.getConnection(DriverManager.java:247)
21.07 20:21:55 [Server] SEVERE at de.staticred.discordbot.db.DataBaseConnection.connect(DataBaseConnection.java:29)
21.07 20:21:55 [Server] SEVERE at de.staticred.discordbot.db.VerifyDAO.isPlayerInDataBase(VerifyDAO.java:149)
21.07 20:21:55 [Server] SEVERE at de.staticred.discordbot.bungeeevents.LeaveEvent.onLeave(LeaveEvent.java:23)
21.07 20:21:55 [Server] SEVERE at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
21.07 20:21:55 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21.07 20:21:55 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:498)
21.07 20:21:55 [Server] SEVERE at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
21.07 20:21:55 [Server] SEVERE at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
21.07 20:21:55 [Server] SEVERE at bungeepluginmanager.ModifiedPluginEventBus.post(ModifiedPluginEventBus.java:33)
21.07 20:21:55 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
21.07 20:21:55 [Server] SEVERE at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:100)
21.07 20:21:55 [Server] SEVERE at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:63)
21.07 20:21:55 [Server] SEVERE at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
```

**Comment by StaticFX** [comment]
21.07 20:21:55 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

https://stackoverflow.com/questions/6865538/solving-a-communications-link-failure-with-jdbc-and-mysql

The plugin works on my database and the ones of my friends.

**Comment by StaticFX** [comment]
You can check if the server is reachable over a link like here: "jdbc:mysql://" + host + ":" + port + "/" + url Then just replace the placeholders by what you put into your config, in my case it would be: jdbc:mysql://localhost:3306/verify

**Comment by StaticFX** [comment]
Are you using a mysql database or another kind of database system?

**Comment by NeadApTar** [comment]
I am using MySQL. The rest of the plugins connected successfully.
