### ISSUE TITLE
Accept command - Error

### ISSUE THREAD

**Issue by NeadApTar** [StaticFX/DiscordBotBungee#8]
When I press the accept button or write accept command.

```22.07 23:29:32 [Server] WARNING Error in dispatching command
22.07 23:29:32 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
22.07 23:29:32 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657)
22.07 23:29:32 [Server] INFO at java.util.ArrayList.get(ArrayList.java:433)
22.07 23:29:32 [Server] INFO at de.staticred.discordbot.Main.updateRoles(Main.java:181)
22.07 23:29:32 [Server] INFO at de.staticred.discordbot.bungeecommands.MCVerifyCommandExecutor.execute(MCVerifyCommandExecutor.java:64)
22.07 23:29:32 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192)
22.07 23:29:32 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
22.07 23:29:32 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:186)
22.07 23:29:32 [Server] INFO at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:66)
22.07 23:29:32 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:110)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
22.07 23:29:32 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
22.07 23:29:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
22.07 23:29:32 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
22.07 23:29:32 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
```

**Comment by StaticFX** [comment]
IndexOutOfBoundsException: Index: 0, Size: 0 the Bot tries to give you a role, which does not exist on the discord server

**Comment by NeadApTar** [comment]
Hmm, okay, my mistake.  Add a message that the plugin didn't find a role with this ID :D

**Comment by NeadApTar** [comment]
I rechecked the Role ID, everything is correct in the configuration file.

**Comment by StaticFX** [comment]
Are you given the Role ID as a String? WIth '' at the start, example: '723878463257444396'

**Comment by NeadApTar** [comment]
With `'` and without `'`. Same error

**Comment by StaticFX** [comment]
You set use ids to true in die config.yml?

**Comment by NeadApTar** [comment]
useTokens or what do I need to enable?

**Comment by StaticFX** [comment]
Yes

**Comment by NeadApTar** [comment]
Now I have this error. And can you rename it to useRoleID or something like that? Or change the description of useTokens, because it is not clear that refers to the Discord role.

```23.07 19:10:46 [Server] WARNING Error in dispatching command
23.07 19:10:46 [Server] INFO java.lang.IllegalArgumentException: Role may not be null
23.07 19:10:46 [Server] INFO at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:56)
23.07 19:10:46 [Server] INFO at net.dv8tion.jda.internal.entities.GuildImpl.addRoleToMember(GuildImpl.java:977)
23.07 19:10:46 [Server] INFO at de.staticred.discordbot.Main.updateRoles(Main.java:193)
23.07 19:10:46 [Server] INFO at de.staticred.discordbot.bungeecommands.MCVerifyCommandExecutor.execute(MCVerifyCommandExecutor.java:64)
```

**Comment by StaticFX** [comment]
Role may not be null is pretty much the same error. Be sure to not use any kind of ' or " because otherwiese the plugin can't get a long out of it. Or just wait for the newest update, it will fix a few things and will probably come out today or tomorrow

**Comment by NeadApTar** [comment]
I updated plugin to version 1.4.0, but error "Role may not be null" remains. I'm set verifyRole with `'` and without it.

Config file:
```yml
UseSQL: true
SQL_USER: login
SQL_PASSWORD: 'pass'
SQL_DATABASE: data_base?useSSL=false
SQL_HOST: 127.0.0.1
SQL_PORT: 3306
USE_DISCORDSRV: false
SRV_USER: root
SRV_PASSWORD: ''
SRV_HOST: localhost
SRV_PORT: '3306'
SRV_DATABASE: discordsrv
prefix: '&8[&6DiscordBot&8] '
bot-token: token
discordBotActivityType: watching
discordBotActivity: '!help'
streamingLink: ''
verifycommand: discord
syncNickName: true
useTokens: true
verifyRole: 730385770199777280
channelID: '643435021721403393'
forceCleanChannel: false
Setuped: true
configVersion: 1.1.1
```

**Comment by StaticFX** [comment]
Your config looks fine, maybe your discord.yml is not correct. How are you getting the role ids? Just rightclick on the role and click copy id.

**Comment by NeadApTar** [comment]
Yup, via rightclick.

**Comment by NeadApTar** [comment]
I didn't edit discord.yml because I don't need to give additional roles.

**Comment by StaticFX** [comment]
Then try it with the role names. If the id Option is not working. I will check the code later. Maybe i did an error on that.

**Comment by NeadApTar** [comment]
Now is `Name may not be empty`

**Comment by StaticFX** [comment]
Okay i will check, maybe give you a new debug version of the plugin. Please be a bit patient, never saw that kind of bug

**Comment by StaticFX** [comment]
[Beta file.zip](https://github.com/StaticFX/DiscordBotBungee/files/4974521/Beta.file.zip)
Okay try with this now, be sure to wirte /db debug before you verify yourself (so it is set to true). Afterwards if it failed send me the log

**Comment by NeadApTar** [comment]
![image](https://user-images.githubusercontent.com/34768994/88466479-50f7e280-ced5-11ea-94de-d5a1d26d92aa.png)

**Comment by StaticFX** [comment]
Ok, so first the plugin isn't checking for your verify group. So nothing stands in there, or you didn't put a '' around the number. Second you have a group called verify in you discord.yml, but the token you registered is 0, so either you did put a string in there, or you did not put any number in there. But my question is. Why are you using the discord.yml if you can just set a verify role in the config, and then just let the discord.yml clean

**Comment by NeadApTar** [comment]
I wrote above, I didn't edit the discord.yml. Plugin did it after "/setup":
```yml
Groups:
- default
default:
  groupName: default
  permission: perm.default
  dynamicGroup: false
```
 Again, I already wrote, I tried to put the role ID in `'` and without `'`. This didn't change anything, the error remained same.

**Comment by NeadApTar** [comment]
Ok, I removed all from discord.yml and put Role ID in config.yml without `'`, and the error disappeared, but bot didn't give role to me. If I add `'`, this error appears again `Role may not be null`
![image](https://user-images.githubusercontent.com/34768994/88483689-463f5b00-cf72-11ea-9010-229c808fcdef.png)

**Comment by StaticFX** [comment]
Try with this one
[file.zip](https://github.com/StaticFX/DiscordBotBungee/files/4977907/file.zip)

**Comment by NeadApTar** [comment]
Everything is fine now
![image](https://user-images.githubusercontent.com/34768994/88484146-4db43380-cf75-11ea-9bbe-d683133c4957.png)
