### ISSUE TITLE
Error by /discord update

### ISSUE THREAD

**Issue by leanderlingens** [StaticFX/DiscordBotBungee#9]
[17:07:03] [WARN]: Error in dispatching command
java.lang.NullPointerException: null
        at de.staticred.discordbot.db.VerifyDAO.hasDiscordID(VerifyDAO.java:251) ~[?:?]
        at de.staticred.discordbot.bungeecommands.MCVerifyCommandExecutor.execute(MCVerifyCommandExecutor.java:145) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:197) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:148) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:147) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:93) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:117) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at me.neznamy.tab.platforms.bungee.Main$2.channelRead(Main.java:108) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:7aa76d5:unknown]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by jotapedroefe** [comment]
Hello @Katzatrophe sorry that this issue got lost on github, we now use a discord server for support, you can find an invite [here](https://discord.gg/djqVDdx), but if you did not end up using the plugin feel free to try the latest version now and see how it is.

**Comment by leanderlingens** [comment]
Thx, I close the Issue.

**Comment by leanderlingens** [comment]
Hello @jotapedroefe,

can you please delete the issue?
